### ISSUE TITLE
Add fixed designs from Griskevicius et al (2011)

### ISSUE THREAD

**Issue by drbenvincent** [drbenvincent/darc-experiments-python#41]
Griskevicius et al (2011) provide a set of 7 fixed delay discounting questions and 7 fixed risky choice questions. It would be useful to include these, in the same way that we include the 27-item fixed set from Kirby.

It could be instructive to include these in the parameter recovery simulations so that we can just have another point of comparison for our approach.

**Delay Discounting Questions**

- £100 tomorrow, or £110 ninety days from now?
- £100 tomorrow, or £120 ninety days from now?
- £100 tomorrow, or £130 ninety days from now? 
- £100 tomorrow, or £140 ninety days from now?
- £100 tomorrow, or £150 ninety days from now? 
- £100 tomorrow, or £160 ninety days from now? 
- £100 tomorrow, or £170 ninety days from now? 

**Risky Choice Questions**

- a 50% chance of getting £800, or  £100 for sure?  
- a 50% chance of getting £800, or  £200 for sure? 
- a 50% chance of getting £800, or  £300 for sure? 
- a 50% chance of getting £800, or £400 for sure? 
- a 50% chance of getting £800, or £500 for sure? 
-  a 50% chance of getting £800, or £600 for sure? 
- a 50% chance of getting £800, or  £700 for sure? 

**Tasks**
- [x] add class for delayed choices
- [x] add class for risky choices
- [x] add basic unit tests

**Reference**
Griskevicius, V., Tybur, J. M., Delton, A. W., & Robertson, T. E. (2011). The influence of mortality and socioeconomic status on risk and delayed rewards: A life history theory approach. Journal of Personality and Social Psychology, 100(6), 1015–26. http://doi.org/10.1037/a0022403
